#!/usr/bin/env python3
"""
Complete P7 batch processor - one command to process all sessions.

This script processes all P7 sessions (P7_1 to P7_5) in one go:
  1. GoPro QR sync (all sessions)
  2. PrimeColor sync (all sessions)
  3. Frame extraction + stable detection + calibration (P7_2 only)
  4. Generate individual YAMLs (using shared cam19_refined.yaml + calibration.json)
  5. Distribute GT (all sessions)

Key assumptions:
  - cam19_refined.yaml exists (created during process_blade_session.py)
  - All P7 sessions share the same cam19_refined.yaml
  - Calibration is done once on P7_2, shared across all sessions
  - GoPro videos are already organized in per-session structure

Usage:
    python workflow/process_p7_complete.py \
        --organized_dir /Volumes/FastACIS/csl_11_5/organized \
        --mocap_dir /Volumes/T7/csl \
        --output_dir /Volumes/FastACIS/csl_11_5/synced \
        --anchor_video /Volumes/FastACIS/csl_11_5/organized/qr_sync.mp4 \
        --cam19_refined /Volumes/T7/csl/P7_2/cam19_refined.yaml \
        --calibration_session P7_2 \
        --start_time 334 \
        --duration 292 \
        --sessions P7_1 P7_2 P7_3 P7_4 P7_5

After running, all P7 sessions will have:
  - Synced videos (GoPro + PrimeColor)
  - Individual camera YAMLs (17 files, shared from P7_2)
  - Distributed GT data (skeleton + blade edges)
"""

import os
import sys
import argparse
import subprocess
import shutil
import json
from pathlib import Path
from typing import List

# Add csl_pipeline paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CSL_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, os.path.join(CSL_ROOT, "scripts"))
sys.path.insert(0, os.path.join(CSL_ROOT, "sync"))

# Terminal colors
class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'


def print_header(msg):
    print(f"\n{Colors.HEADER}{'='*70}")
    print(f"{msg}")
    print(f"{'='*70}{Colors.ENDC}\n")


def print_phase(phase_num, total_phases, msg):
    print(f"\n{Colors.OKBLUE}{'='*70}")
    print(f"[Phase {phase_num}/{total_phases}] {msg}")
    print(f"{'='*70}{Colors.ENDC}")


def print_success(msg):
    print(f"{Colors.OKGREEN}✓ {msg}{Colors.ENDC}")


def print_warning(msg):
    print(f"{Colors.WARNING}⚠ {msg}{Colors.ENDC}")


def print_error(msg):
    print(f"{Colors.FAIL}✗ {msg}{Colors.ENDC}")


def run_command(cmd, description, check=True):
    """Run shell command with logging."""
    print(f"\n  Running: {description}")
    result = subprocess.run(cmd, capture_output=False)

    if check and result.returncode != 0:
        print_error(f"{description} failed with exit code {result.returncode}")
        sys.exit(1)

    return result.returncode == 0


def check_file_exists(filepath, required=True):
    """Check if file exists."""
    path = Path(filepath)
    if path.exists():
        return True
    else:
        if required:
            print_error(f"Required file not found: {filepath}")
            sys.exit(1)
        else:
            print_warning(f"Optional file not found: {filepath}")
            return False


def phase1_gopro_sync(organized_dir, output_dir, anchor_video, sessions):
    """Phase 1: Synchronize all GoPro sessions."""
    print_phase(1, 5, "GoPro QR Synchronization")

    check_file_exists(anchor_video)

    for session in sessions:
        session_input = Path(organized_dir) / session
        session_output = Path(output_dir) / f"{session}_sync"

        # Check if already synced
        meta_file = session_output / "cameras_synced" / "meta_info.json"
        if meta_file.exists():
            print_success(f"{session}: Already synced")
            continue

        print(f"\n  Syncing {session}...")

        cmd = [
            "python", os.path.join(CSL_ROOT, "sync", "sync_gopro_qr_fast.py"),
            "--input_dir", str(session_input),
            "--output_dir", str(session_output),
            "--anchor_video", anchor_video,
            "--verify"
        ]

        run_command(cmd, f"GoPro sync for {session}")

    print_success("All GoPro sessions synchronized")


def phase2_primecolor_sync(organized_dir, mocap_dir, output_dir, sessions, anchor_video):
    """Phase 2: Synchronize all PrimeColor sessions."""
    print_phase(2, 5, "PrimeColor Synchronization")

    for session in sessions:
        session_mocap = Path(mocap_dir) / session
        session_synced = Path(output_dir) / f"{session}_sync" / "cameras_synced"

        # Check if PrimeColor video exists (generated by process_mocap_session.py)
        primecolor_input = session_mocap / "video.mp4"
        if not primecolor_input.exists():
            print_warning(f"{session}: video.mp4 not found, skipping")
            continue

        # Check if already synced
        primecolor_output = session_synced / "cam19" / "primecolor_synced.mp4"
        sync_mapping = session_synced / "cam19" / "sync_mapping.json"
        if primecolor_output.exists() and sync_mapping.exists():
            print_success(f"{session}: Already synced")
            continue

        print(f"\n  Syncing {session}...")

        # Find a synced GoPro video for metadata (fps, duration).
        # We don't scan it for QR codes - the pre-computed offset from Phase 1 is used instead.
        gopro_video = None
        for cam_dir in sorted(session_synced.glob("cam*")):
            if cam_dir.is_dir() and cam_dir.name != "cam19":
                videos = list(cam_dir.glob("*.MP4")) + list(cam_dir.glob("*.mp4"))
                if videos:
                    gopro_video = videos[0]
                    break

        if not gopro_video:
            print_error(f"{session}: No synced GoPro video found, skipping")
            continue

        # Read Phase 1 meta_info.json to get pre-computed GoPro anchor offset.
        # The synced video's effective anchor offset = anchor_offset - sync_offset
        # because sync_offset seconds were trimmed from the beginning.
        meta_file = session_synced / "meta_info.json"
        gopro_anchor_offset = None

        if meta_file.exists():
            with open(meta_file) as f:
                meta = json.load(f)

            # Find cam1's entry (use same camera as gopro_video)
            cam_name = gopro_video.parent.name
            for key, cam_meta in meta.get("cameras", {}).items():
                if key.startswith(cam_name + "/"):
                    anchor_off = cam_meta.get("anchor_offset")
                    sync_off = cam_meta.get("sync_offset", 0.0)
                    if anchor_off is not None:
                        gopro_anchor_offset = anchor_off - sync_off
                        print(f"  Pre-computed GoPro anchor offset: {gopro_anchor_offset:.6f}s")
                        print(f"    (anchor_offset={anchor_off:.6f} - sync_offset={sync_off:.6f})")
                    break

        if gopro_anchor_offset is None:
            print_warning(f"{session}: Could not read anchor offset from meta_info.json, will scan QR codes")

        cmd = [
            "python", os.path.join(CSL_ROOT, "sync", "sync_primecolor_to_gopro_precise.py"),
            "--gopro_video", str(gopro_video),
            "--primecolor_video", str(primecolor_input),
            "--anchor_video", str(anchor_video),
            "--output_dir", str(session_synced / "cam19"),
            "--scan_duration", "240",
            "--min_detections", "30",
            "--frame_step", "10",
            "--skip_csv",
            "--gpu"
        ]

        if gopro_anchor_offset is not None:
            cmd.extend(["--gopro_anchor_offset", str(gopro_anchor_offset)])

        run_command(cmd, f"PrimeColor sync for {session}")

    print_success("All PrimeColor videos synchronized")


def phase3_calibration(calibration_session, output_dir, start_time, duration, fps=5):
    """Phase 3: Calibration on one session (extract frames + stable + calibrate)."""
    print_phase(3, 5, f"17-Camera Calibration (using {calibration_session})")

    session_synced = Path(output_dir) / f"{calibration_session}_sync" / "cameras_synced"

    # Check if calibration already exists
    calib_json = session_synced / "original_stable" / "calibration.json"
    if calib_json.exists():
        print_success("calibration.json already exists")
        try:
            with open(calib_json) as f:
                data = json.load(f)
                rms = data.get("error", {}).get("rms", -1)
                if rms > 0:
                    print_success(f"RMS error: {rms:.2f} pixels")
        except:
            pass
        return

    # Step 3.1: Extract frames
    print("\n  [3.1] Extracting frames...")
    output_frames = session_synced / "original"

    # Check that most cameras have extracted frames (not just total count)
    cam_dirs_with_frames = [d for d in output_frames.glob("cam*") if d.is_dir() and len(list(d.glob("frame_*.jpg"))) > 10]
    if len(cam_dirs_with_frames) >= 15:
        total = sum(len(list(d.glob("frame_*.jpg"))) for d in cam_dirs_with_frames)
        print_success(f"Frames already extracted ({total} images across {len(cam_dirs_with_frames)} cameras)")
    else:
        output_frames.mkdir(parents=True, exist_ok=True)

        # Get cameras
        cameras = []
        for cam_dir in sorted(session_synced.glob("cam*")):
            if cam_dir.is_dir() and cam_dir.name != "cam19":
                videos = list(cam_dir.glob("*.MP4")) + list(cam_dir.glob("*.mp4"))
                if videos:
                    cameras.append((cam_dir.name, videos[0]))

        cam19_video = session_synced / "cam19" / "primecolor_synced.mp4"
        if cam19_video.exists():
            cameras.append(("cam19", cam19_video))

        for cam_name, video_path in cameras:
            cam_output = output_frames / cam_name
            cam_output.mkdir(parents=True, exist_ok=True)

            existing = list(cam_output.glob("frame_*.jpg"))
            if len(existing) > 10:
                print(f"  {cam_name}: Skipping ({len(existing)} frames exist)")
                continue

            print(f"  {cam_name}: Extracting...")

            cmd = [
                "python", os.path.join(CSL_ROOT, "scripts", "convert_video_to_images.py"),
                "--src_tag", str(session_synced),
                "--cam_tags", cam_name,
                "--fps", str(fps),
                "--ss", str(start_time),
                "--duration", str(duration),
                "--format", "jpg"
            ]

            run_command(cmd, f"Extract frames for {cam_name}", check=False)

    # Step 3.2: Find stable frames
    print("\n  [3.2] Detecting stable frames...")
    output_stable = session_synced / "original_stable"

    existing_stable = list(output_stable.glob("cam*/frame_*.jpg"))
    if len(existing_stable) > 50:
        print_success(f"Stable frames already detected ({len(existing_stable)} images)")
    else:
        output_stable.mkdir(parents=True, exist_ok=True)

        board_config = os.path.join(CSL_ROOT, "multical", "asset", "charuco_b1_2.yaml")
        check_file_exists(board_config)

        cmd = [
            "python", os.path.join(CSL_ROOT, "scripts", "find_stable_boards.py"),
            "--recording_tag", str(output_frames),
            "--boards", board_config,
            "--movement_threshold", "5.0",
            "--min_detection_quality", "40",
            "--downsample_rate", "10",
            "--max_frames_per_camera", "500",
            "--copy_stable_frames",
            "--output_suffix", "_stable"
        ]

        run_command(cmd, "Stable frame detection")

    # Step 3.3: Joint calibration
    print("\n  [3.3] Running multical joint calibration...")

    intrinsic_file = os.path.join(CSL_ROOT, "intrinsic_all_17_cameras.json")
    check_file_exists(intrinsic_file)

    board_config = os.path.join(CSL_ROOT, "multical", "asset", "charuco_b1_2.yaml")

    original_cwd = os.getcwd()
    os.chdir(CSL_ROOT)

    try:
        cmd = [
            "python", "-m", "multical.app.calibrate",
            "--image_path", str(output_stable),
            "--boards", board_config,
            "--calibration", intrinsic_file,
            "--camera_pattern", "{camera}",
            "--fix_intrinsic",
            "--limit_images", "1000"
        ]

        run_command(cmd, "Multical joint calibration")

        # Check result
        if calib_json.exists():
            with open(calib_json) as f:
                data = json.load(f)
                rms = data.get("error", {}).get("rms", -1)
                if rms > 0:
                    if rms < 1.6:
                        print_success(f"RMS error: {rms:.2f} pixels (excellent)")
                    elif rms < 2.5:
                        print_success(f"RMS error: {rms:.2f} pixels (good)")
                    else:
                        print_warning(f"RMS error: {rms:.2f} pixels (consider refining)")
        else:
            print_error("calibration.json not created")
            sys.exit(1)

    finally:
        os.chdir(original_cwd)


def phase4_generate_yamls(calibration_session, cam19_refined, output_dir, sessions):
    """Phase 4: Generate individual YAMLs for all sessions (using shared calibration)."""
    print_phase(4, 5, "Generate Individual Camera YAMLs")

    calib_session_synced = Path(output_dir) / f"{calibration_session}_sync" / "cameras_synced"
    calib_json = calib_session_synced / "original_stable" / "calibration.json"

    check_file_exists(calib_json)
    check_file_exists(cam19_refined)

    for session in sessions:
        session_synced = Path(output_dir) / f"{session}_sync" / "cameras_synced"
        output_yaml_dir = session_synced / "individual_cam_params"

        # Check if YAMLs already exist
        existing_yamls = list(output_yaml_dir.glob("cam*.yaml"))
        if len(existing_yamls) >= 17:
            print_success(f"{session}: YAMLs already exist ({len(existing_yamls)} files)")
            continue

        print(f"\n  Generating YAMLs for {session}...")

        output_yaml_dir.mkdir(parents=True, exist_ok=True)

        cmd = [
            "python", os.path.join(CSL_ROOT, "post_calibration", "generate_individual_cam_yaml.py"),
            "--calib_json", str(calib_json),
            "--cam19_yaml", cam19_refined,
            "--output_dir", str(output_yaml_dir)
        ]

        run_command(cmd, f"Generate YAMLs for {session}")

        yaml_files = list(output_yaml_dir.glob("cam*.yaml"))
        print_success(f"  Generated {len(yaml_files)} YAML files")

    print_success("All individual YAMLs generated")


def phase5_distribute_gt(mocap_dir, output_dir, sessions):
    """Phase 5: Create GT symlinks and distribute GT to all sessions."""
    print_phase(5, 5, "Distribute GT Data")

    for session in sessions:
        session_mocap = Path(mocap_dir) / session
        session_synced = Path(output_dir) / f"{session}_sync" / "cameras_synced"
        cam19_dir = session_synced / "cam19"

        # Create symlinks
        print(f"\n  [{session}] Creating GT symlinks...")

        # Skeleton
        src_skeleton = session_mocap / "skeleton_h36m.npy"
        dst_skeleton = cam19_dir / "skeleton_h36m.npy"

        if src_skeleton.exists():
            if not dst_skeleton.exists():
                os.symlink(src_skeleton, dst_skeleton)
                print_success("  skeleton_h36m.npy symlink created")
            else:
                print_success("  skeleton_h36m.npy symlink exists")
        else:
            print_warning(f"  skeleton not found: {src_skeleton}")

        # Blade edges (support multiple blades: Rblade_edges.npy, lblade2_edges.npy, etc.)
        blade_files = sorted(session_mocap.glob("*_edges.npy"))

        # Filter out edge1/edge2 files (we only want the final aligned edges)
        blade_files = [f for f in blade_files
                       if not f.name.endswith("_edge1.npy")
                       and not f.name.endswith("_edge2.npy")]

        if blade_files:
            print(f"  Found {len(blade_files)} blade(s): {', '.join(f.name for f in blade_files)}")

            # Create symlink for each blade (preserve original names)
            for src_blade in blade_files:
                dst_blade = cam19_dir / src_blade.name
                if not dst_blade.exists():
                    os.symlink(src_blade, dst_blade)
                    print_success(f"  {src_blade.name} symlink created")
                else:
                    print_success(f"  {src_blade.name} symlink exists")

            # Create default aligned_edges.npy symlink (points to primary blade)
            # Priority: Rblade > lblade2 > first blade
            primary_blade = None
            for f in blade_files:
                if "Rblade" in f.name:
                    primary_blade = f
                    break
            if not primary_blade:
                for f in blade_files:
                    if "lblade2" in f.name or "lblade" in f.name:
                        primary_blade = f
                        break
            if not primary_blade:
                primary_blade = blade_files[0]

            dst_aligned = cam19_dir / "aligned_edges.npy"
            if not dst_aligned.exists():
                os.symlink(primary_blade, dst_aligned)
                print_success(f"  aligned_edges.npy → {primary_blade.name}")
            else:
                print_success("  aligned_edges.npy symlink exists")
        else:
            print_warning(f"  No blade edges found in {session_mocap}")

        # Distribute GT
        print(f"\n  [{session}] Distributing GT...")

        existing_gt = list(session_synced.glob("cam*/gt/skeleton.npy"))
        if len(existing_gt) >= 16:
            print_success(f"  GT already distributed ({len(existing_gt)} cameras)")
            continue

        cmd = [
            "python", os.path.join(CSL_ROOT, "scripts", "distribute_gt.py"),
            "--session_dir", str(session_synced),
            "--force"
        ]

        run_command(cmd, f"Distribute GT for {session}")

        gt_files = list(session_synced.glob("cam*/gt/skeleton.npy"))
        print_success(f"  GT distributed to {len(gt_files)} cameras")

    print_success("All GT data distributed")


def find_cam19_refined(mocap_dir: Path) -> Path:
    """Search for cam19_refined.yaml in mocap directory tree."""
    print(f"\n  Searching for cam19_refined.yaml in {mocap_dir}...")

    # Search all subdirectories
    yaml_files = list(mocap_dir.glob("*/cam19_refined.yaml"))

    if not yaml_files:
        print_error(f"cam19_refined.yaml not found in {mocap_dir}")
        print_error("Please ensure process_blade_session.py has been run with cam19 refinement")
        sys.exit(1)

    if len(yaml_files) > 1:
        print_warning(f"Multiple cam19_refined.yaml found:")
        for f in yaml_files:
            print(f"    {f}")
        print_warning(f"Using first one: {yaml_files[0]}")

    yaml_path = yaml_files[0]
    print_success(f"Found: {yaml_path}")
    return yaml_path


def main():
    parser = argparse.ArgumentParser(
        description='Complete P7 batch processor - process all sessions in one go',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split('Usage:')[1])

    # Input/Output paths
    parser.add_argument('--organized_dir', required=True,
                        help='GoPro organized directory')
    parser.add_argument('--mocap_dir', required=True,
                        help='Mocap data directory (contains P7_X/)')
    parser.add_argument('--output_dir', required=True,
                        help='Output directory for synced data')

    # Required files
    parser.add_argument('--anchor_video', required=True,
                        help='QR anchor video for GoPro sync')
    parser.add_argument('--cam19_refined', default=None,
                        help='cam19_refined.yaml (if not provided, will auto-search in mocap_dir)')

    # Calibration settings
    parser.add_argument('--calibration_session', default='P7_2',
                        help='Session to use for calibration (default: P7_2)')
    parser.add_argument('--start_time', type=float, default=334,
                        help='Frame extraction start time (seconds)')
    parser.add_argument('--duration', type=float, default=292,
                        help='Frame extraction duration (seconds)')
    parser.add_argument('--fps', type=float, default=5,
                        help='Frame extraction FPS')

    # Sessions to process
    parser.add_argument('--sessions', nargs='+', default=['P7_1', 'P7_2', 'P7_3', 'P7_4', 'P7_5'],
                        help='List of sessions to process')

    args = parser.parse_args()

    # Validate
    organized_dir = Path(args.organized_dir)
    mocap_dir = Path(args.mocap_dir)
    output_dir = Path(args.output_dir)

    if not organized_dir.exists():
        print_error(f"Organized directory not found: {organized_dir}")
        sys.exit(1)

    if not mocap_dir.exists():
        print_error(f"Mocap directory not found: {mocap_dir}")
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    # Auto-search cam19_refined.yaml if not provided
    if args.cam19_refined:
        cam19_refined = Path(args.cam19_refined)
        check_file_exists(cam19_refined)
    else:
        cam19_refined = find_cam19_refined(mocap_dir)

    # Print info
    print_header("P7 Complete Batch Processor")

    print(f"Organized dir:  {organized_dir}")
    print(f"Mocap dir:      {mocap_dir}")
    print(f"Output dir:     {output_dir}")
    print(f"Anchor video:   {args.anchor_video}")
    print(f"cam19 refined:  {cam19_refined}")
    print(f"Calibration:    {args.calibration_session}")
    print(f"Sessions:       {', '.join(args.sessions)}")
    print(f"\nCalibration time range: {args.start_time}s - {args.start_time + args.duration}s")

    # Execute pipeline
    try:
        phase1_gopro_sync(organized_dir, output_dir, args.anchor_video, args.sessions)
        phase2_primecolor_sync(organized_dir, mocap_dir, output_dir, args.sessions, args.anchor_video)
        phase3_calibration(args.calibration_session, output_dir, args.start_time, args.duration, args.fps)
        phase4_generate_yamls(args.calibration_session, cam19_refined, output_dir, args.sessions)
        phase5_distribute_gt(mocap_dir, output_dir, args.sessions)

        # Success summary
        print_header("Pipeline Complete!")

        print(f"Processed sessions: {', '.join(args.sessions)}")
        print(f"Calibration session: {args.calibration_session}")

        calib_json = Path(output_dir) / f"{args.calibration_session}_sync" / "cameras_synced" / "original_stable" / "calibration.json"
        if calib_json.exists():
            print_success(f"Shared calibration: {calib_json}")

        print(f"\nOutput directory: {output_dir}")

        print("\n" + Colors.OKGREEN + Colors.BOLD)
        print("All P7 sessions successfully processed!")
        print(Colors.ENDC)

        print("\nEach session now has:")
        print("  ✓ Synced GoPro videos (16 cameras)")
        print("  ✓ Synced PrimeColor video (60fps)")
        print("  ✓ Individual camera YAMLs (17 files)")
        print("  ✓ Distributed GT data (skeleton + blade edges)")

        print("\nNext steps:")
        print("  - Verify GT temporal alignment:")
        print(f"    python post_calibration/verify_gt_offset.py --session_dir <session>/cameras_synced --camera cam1")
        print("  - Start training/inference!")

    except KeyboardInterrupt:
        print(f"\n\n{Colors.WARNING}Pipeline interrupted by user{Colors.ENDC}")
        sys.exit(1)
    except Exception as e:
        print_error(f"Pipeline failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
